# Spring Application Name
spring.application.name=geops-api

# Frontend URL used for CORS (development default)
frontend.url=${FRONTEND_URL}
prod.frontend.url=${PROD_FRONTEND_URL}
prod.api.url=${PROD_API_URL}

# Spring DataSource Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Spring Data JPA Configuration
spring.jpa.show-sql=true

# Spring Data JPA Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.naming.physical-strategy=com.geopslabs.geops.api.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy

# Elements take their values form maven pom.xml build-related information
documentation.application.description=@project.description@
documentation.application.version=@project.version@

server.max-http-request-header-size=128KB
server.tomcat.max-http-header-size=131072

# Security Configuration
authorization.jwt.secret=${JWT_SECRET}
authorization.jwt.expiration.days=7